name       : libgee
version    : 0.20.2
release    : 13
source     :
    - https://download.gnome.org/sources/libgee/0.20/libgee-0.20.2.tar.xz : 9e035c4b755f46bfae70ba81cdcf8328b03f554373cec8c816e8b5680f85353c
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
description: |
    The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
builddeps  :
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
