name       : libgee
version    : 0.20.3
release    : 15
source     :
    - https://download.gnome.org/sources/libgee/0.20/libgee-0.20.3.tar.xz : d0b5edefc88cbca5f1709d19fa62aef490922c6577a14ac4e7b085507911a5de
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
description: |
    The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
builddeps  :
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
