name        : libgee
version     : 0.18.0
release     : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libgee/0.18/libgee-0.18.0.tar.xz : 4ad99ef937d071b4883c061df40bfe233f7649d50c354cf81235f180b4244399
license     : GPL-3.0+
summary     : The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
builddeps   :
    - vala
description : |
    The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
