name       : libgee
version    : 0.20.1
release    : 11
source     :
    - https://download.gnome.org/sources/libgee/0.20/libgee-0.20.1.tar.xz : bb2802d29a518e8c6d2992884691f06ccfcc25792a5686178575c7111fea4630
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : The libgee package is a collection library providing GObject based interfaces
    and classes for commonly used data structures.
description: |
    The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
builddeps  :
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
