name       : libgee
version    : 0.20.0
release    : 9
source     :
    - https://download.gnome.org/sources/libgee/0.20/libgee-0.20.0.tar.xz : 21308ba3ed77646dda2e724c0e8d5a2f8d101fb05e078975a532d7887223c2bb
license    : GPL-3.0
component  : desktop.gnome.core
summary    : The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
builddeps  :
    - vala
description: |
    The libgee package is a collection library providing GObject based interfaces and classes for commonly used data structures.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
